name: Initial Deployment Pipeline
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "- Lint the code and run unit tests" >> $GITHUB_STEP_SUMMARY

  build:
    needs: [integration]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "- Build the artifact" >> $GITHUB_STEP_SUMMARY

  test-artifact:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "- Simulate and test the artifact" >> $GITHUB_STEP_SUMMARY

  development:
    environment: Development
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Auto-deploy the artifact to the development environment with message '${{vars.MSG}}'" >> $GITHUB_STEP_SUMMARY

  staging:
    environment: Staging
    needs: [development, test-artifact]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "After development environment is deployed..." >> $GITHUB_STEP_SUMMARY
          echo "and after the artifact tests have passed..." >> $GITHUB_STEP_SUMMARY
          echo "- Auto-deploy the artifact to the staging environment with message '${{vars.MSG}}'" >> $GITHUB_STEP_SUMMARY

  test-staging:
    needs: [staging]
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Test the staging environment" >> $GITHUB_STEP_SUMMARY

  production:
    environment: Production
    needs: [staging, test-staging]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "After staging environment is deployed..." >> $GITHUB_STEP_SUMMARY
          echo "and after the staging tests have passed..." >> $GITHUB_STEP_SUMMARY
          echo "require a review before deploying to the production environment, then..." >> $GITHUB_STEP_SUMMARY
          echo "- Deploy the artifact to the production environment with message '${{vars.MSG}}'" >> $GITHUB_STEP_SUMMARY

  test-production:
    needs: [production]
    runs-on: ubuntu-latest
    steps:
      - run: echo "- Test the artifact in the production environment" >> $GITHUB_STEP_SUMMARY
      - run: echo "# All tests and deployments have completed successfully!" >> $GITHUB_STEP_SUMMARY
